FROM openjdk:8

# Install mpstat command  
RUN apt-get update && apt-get -y install sysstat

WORKDIR .
EXPOSE 8081
CMD java -jar /var/mark59/dataHunter/target/dataHunter.war --spring.profiles.active=h2 --port=8081
