CREATE TABLE IF NOT EXISTS POLICIES (
  APPLICATION 	VARCHAR(64) NOT NULL,
  IDENTIFIER 	VARCHAR(512) NOT NULL,
  LIFECYCLE 	VARCHAR(64) NOT NULL,
  USEABILITY 	VARCHAR(8) NOT NULL,
  OTHERDATA 	VARCHAR(64) NOT NULL,
  CREATED 		DATETIME NOT NULL,
  UPDATED 		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  EPOCHTIME 	BIGINT(20) NOT NULL DEFAULT 0,
  PRIMARY KEY (APPLICATION, IDENTIFIER, LIFECYCLE)
 ); 
