CREATE TABLE IF NOT EXISTS POLICIES (
  APPLICATION 	VARCHAR(64) NOT NULL,
  IDENTIFIER 	VARCHAR(512) NOT NULL,
  LIFECYCLE 	VARCHAR(64) NOT NULL,
  USEABILITY 	VARCHAR(8) NOT NULL,
  OTHERDATA 	VARCHAR(512) NOT NULL,
  CREATED   	TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
  UPDATED   	TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  EPOCHTIME 	BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (APPLICATION, IDENTIFIER, LIFECYCLE)
 ); 
