
-- DROP DATABASE IF EXISTS datahunterdb;
CREATE DATABASE datahunterdb CHARACTER SET utf8mb4  COLLATE utf8mb4_bin; 

USE datahunterdb;


-- PLEASE RUN  "MYSQLcreateAdminUser.sql"  TO CREATE THE 'ADMIN' USER IF YOU HAVE NOT ALREADY DONE SO.  

-- Note that character set utf8mb4 is the default from MySQL 8.0.
-- The collation for the database is set to utf8mb4_bin
-- Useful at at is allows for stuff like case-sensitive eventmapping matching.  Also aligns H2 database and Java case sensitive sorting.          


-- create tables  -- 


CREATE TABLE IF NOT EXISTS  POLICIES (
  APPLICATION VARCHAR(64) NOT NULL,
  IDENTIFIER 	VARCHAR(512) NOT NULL,
  LIFECYCLE 	VARCHAR(64) NOT NULL,
  USEABILITY 	ENUM('UNUSED','USED','REUSABLE','UNPAIRED') NOT NULL,
  OTHERDATA  	MEDIUMTEXT NOT NULL,
  CREATED   	DATETIME NOT NULL,
  UPDATED   	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  EPOCHTIME  	BIGINT  NOT NULL DEFAULT '0',
  PRIMARY KEY (APPLICATION,IDENTIFIER,LIFECYCLE),
  KEY APPLICATION (APPLICATION)
); 


CREATE TABLE IF NOT EXISTS REFERENCE (
  APPLICATION VARCHAR(64) NOT NULL,
  PROPERTY	  VARCHAR(128) NOT NULL,
  VALUE 	  VARCHAR(128) NOT NULL,
  DESCRIPTION VARCHAR(512) DEFAULT NULL,
  PRIMARY KEY (APPLICATION,PROPERTY)
); 
  