FROM openjdk:8-jdk-stretch

# Install mpstat command  
RUN apt-get update && apt-get -y install sysstat

WORKDIR .
EXPOSE 8083
CMD java -jar /var/mark59/mark59-trends/target/mark59-trends.war --spring.profiles.active=h2tcpserver --port=8083 --h2.port=9092
