FROM openjdk:8

# Install mpstat command  
RUN apt-get update && apt-get -y install sysstat

WORKDIR .
EXPOSE 8081
CMD java -jar /var/mark59/mark59-datahunter/target/mark59-datahunter.war --spring.profiles.active=h2 --port=8081
